# Generated by Django 5.0 on 2024-01-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Haber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gazeteci", models.CharField(max_length=50)),
                ("baslik", models.CharField(max_length=50)),
                ("metin", models.TextField()),
                ("sehir", models.CharField(max_length=50)),
                ("yayın_tarihi", models.DateField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateField(auto_now=True)),
                ("aktif", models.BooleanField(default=True)),
            ],
        ),
    ]
