# Generated by Django 5.0 on 2024-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haberler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gazeteci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=50)),
                ("soyisim", models.CharField(max_length=50)),
                ("biyografi", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
