# Generated by Django 5.0 on 2024-01-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haberler", "0002_gazeteci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haber",
            name="gazeteci",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="haberler.gazeteci"
            ),
        ),
    ]
