# Generated by Django 5.0 on 2024-01-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haberler", "0005_alter_haber_gazeteci_delete_gazeteci"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gazeteci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=50)),
                ("soyisim", models.CharField(max_length=50)),
                ("biyografi", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="haber",
            name="gazeteci",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="haberler",
                to="haberler.gazeteci",
            ),
        ),
    ]
